name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository_owner == 'packit'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Hugo Deploy GitHub Pages
        # [TODO] Switch back to the official action once the #66 has been merged
        # and released
        uses: mfocko/hugo-deploy-gh-pages@31154be6dc01b324913f349225c57a5c03bffd8e
        # uses: benmatselby/hugo-deploy-gh-pages@v2.4.0
        env:
          CNAME: status.packit.dev
          GITHUB_ACTOR: usercont-release-bot
          HUGO_VERSION: 0.98.0
          HUGO_EXTENDED: true
          TARGET_REPO: packit/status-github-pages
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.RELEASEBOT_GITHUB_TOKEN }}
